
export enum TILE_TYPE_ENUM{
    WALL_ROW = 'WALL_ROW',
    WALL_COLUMN = 'WALL_COLUMN',
    WALL_LEFT_TOP = 'WALL_LEFT_TOP',
    WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
    WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
    WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
    CLIFF_CENTER = 'CLIFF_CENTER',
    CLIFF_LEFT = 'CLIFF_LEFT',
    CLIFF_RIGHT = 'CLIFF_RIGHT',
    FLOOR = 'FLOOR',

}

export enum EVENT_ENUM{
    NEXT_LEVEL = 'NEXT_LEVEL',
    PLAYER_CTRL = 'PLAYER_CTRL',
    PLAYER_MOVE_END = 'PLAYER_MOVE_END',
    PLAYER_BORN = 'PLAYER_BORN',
    ATTACK_PLAYER = 'ATTACK_PLAYER',
    ATTACK_ENEMY = 'ATTACK_ENEMY',
    DOOR_OPEN ='DOOR_OPEN',
    SHOW_SMOKE = 'SHOW_SMOKE',
    SCREEN_SHAKE = 'SCREEN_SHAKE',

    RECORD_STEP = 'RECORD_STEP',
    REVOKE_STEP = 'REVOKE_STEP',

    RESTART_LEVEL = 'RESTART_LEVEL',
    OUT_BATTLE = 'OUT_BATTLE'
}

export enum CONTROLLER_ENUM{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT'

}

export enum FSM_PARAMS_TYPE_ENUM{
    TRIGGER = 'TRIGGER',
    NUMBER = 'NUMBER'

}

export enum PARAMS_NAME_ENUM {
    DIRECTION = 'DIRECTION',

    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',

    BLOCKFRONT = 'BLOCKFRONT',
    BLOCKBACK = 'BLOCKBACK',
    BLOCKLEFT = 'BLOCKLEFT',
    BLOCKRIGHT = 'BLOCKRIGHT',
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',

    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH',

    SPIKES_CUR_COUNT = 'SPIKES_CUR_COUNT',
    SPIKES_TOTAL_COUNT = 'SPIKES_TOTAL_COUNT',
    SPIKES_CUR_CLIP = "SPIKES_CUR_CLIP",
    SPIKES_TOTAL_CLIPS = "SPIKES_TOTAL_CLIPS"
}

export enum DIRECTION_ENUM{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT'
}

export enum ENTITY_STATE_ENUM{
    // 共 12 种状态
    IDLE = 'IDLE',
    TURNLEFT = 'TURNLEFT',
    TURNRIGHT = 'TURNRIGHT',
    BLOCKFRONT = 'BLOCKFRONT',
    BLOCKBACK = 'BLOCKBACK',
    BLOCKLEFT = 'BLOCKLEFT',
    BLOCKRIGHT = 'BLOCKRIGHT',
    BLOCKTURNLEFT = 'BLOCKTURNLEFT',
    BLOCKTURNRIGHT = 'BLOCKTURNRIGHT',
    ATTACK = 'ATTACK',
    DEATH = 'DEATH',
    AIRDEATH = 'AIRDEATH',

}

export enum DIRECTION_ORDER_ENUM{ // 数字枚举具有双向映射的特点
    TOP = 0,
    BOTTOM = 1,
    LEFT = 2,
    RIGHT = 3
}

export enum ENTITY_TYPE_ENUM{
    PLAYER = 'PLAYER',
    SKELETON_WOODEN = 'SKELETON_WOODEN',
    SKELETON_IRON = 'SKELETON_IRON',
    DOOR= 'DOOR',
    BURST = 'BURST',
    SMOKE = 'SMOKE',

}

/*********************关于Spikes的枚举 start***************************/
export enum SPIKES_TYPE_ENUM{
    SPIKES_ONE = 'SPIKES_ONE',
    SPIKES_TWO = 'SPIKES_TWO',
    SPIKES_THREE = 'SPIKES_THREE',
    SPIKES_FOUR = 'SPIKES_FOUR',
}

export enum SPRIKES_TYPE_MAP_TOTAL_CLIPS_ENUM{ // 数字枚举具有双向映射的特点
    // 每种尖刺类型对应有多少个动画剪辑种类
    SPIKES_ONE = 2,
    SPIKES_TWO = 3,
    SPIKES_THREE = 4,
    SPIKES_FOUR = 5,
}


export enum SPIKES_SHOW_ORDER_ENUM{
    ZERO = 'ZERO',
    ONE = 'ONE',
    TWO =  'TWO',
    THREE = 'THREE',
    FOUR = 'FOUR',
    FIVE = 'FIVE',

}

export enum SPRIKES_ORDER_MAP_NUMBER_ENUM{ // 数字枚举具有双向映射的特点
    ZERO = 0,
    ONE = 1,
    TWO =  2,
    THREE = 3,
    FOUR = 4,
    FIVE = 5,
}
/*********************关于Spikes的枚举 end***************************/

export enum SHAKE_DIRECTION_ENUM{
    TOP = 'TOP',
    BOTTOM = 'BOTTOM',
    LEFT = 'LEFT',
    RIGHT = 'RIGHT'
}

export enum SCREEN_ENUM{
    // 注意！要与场景的命名一致
    Loading = 'Loading',
    Start = 'Start',
    Battle = 'Battle'
}
